### PR TITLE
Fix import

### PR DESCRIPTION
**Pull request by ravanscafi**
Otherwise, I was getting the following error:

```
Unable to load extension: No module named jinja2_slug
```

### CODE REVIEW

**Comment by xsteadfastx** [comment]
with what python version are you trying to use this? could you provide a example code snippet or directory structure where you use it? im using this for years without any of this problems.

**Comment by ravanscafi** [comment]
Sure @xsteadfastx 

I'm using [CookieCutter](https://github.com/cookiecutter/cookiecutter). It uses Jinja2 templates.
You can enable extensions on the config, like [the docs says](https://cookiecutter.readthedocs.io/en/latest/advanced/template_extensions.html?highlight=_extensions):

```json
{
    "year": "{% now 'utc', '%Y' %}",
    "_extensions": ["jinja2_time.TimeExtension"]
}
```

It works like a charm with `jinja2_time`, but it wasn't working when I tried with something like this:

```json
{
    "user_name": "John Snow",
    "repo_name": "{{ cookiecutter.user_name | slug }}",
    "_extensions": ["jinja2_slug.SlugExtension"]
}
```

I tried both with python 2.7 and 3.7 but with no luck. So I took inspiration from [jinja2-time \_\_init__ file](https://github.com/hackebrot/jinja2-time/blob/master/jinja2_time/__init__.py#L3) and did the same for this package. It solved the problem, everything worked like a charm.

Am I doing something wrong? Thanks for the help.

**Comment by xsteadfastx** [comment]
i promise you to look at it tomorrow :) long time ago i did something on
this and i really have to check what i done there and what the heck i
thought while doing it ;-)

**Comment by xsteadfastx** [comment]
it really gets me... it shouldnt make any difference. i prefer to use absolut imports and not relatives... but i dont know why this should matter.

**Comment by xsteadfastx** [comment]
@ravanscafi could you check the version in master out? i also converted everything to a newer workflow... to poetry. if it works for you i would push the new version to pypi.

**Comment by ravanscafi** [comment]
Sure, I will test it this weekend!

**Comment by ravanscafi** [comment]
Ok @xsteadfastx, everything is working :)

**Comment by xsteadfastx** [comment]
> Ok @xsteadfastx, everything is working :)

its on pypi. thanks for your input!

**Pull request merged**
